---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	route(route)
	plan(plan)
	retrieve(retrieve)
	grade(grade)
	rewrite(rewrite)
	generate(generate)
	respond(respond)
	__end__([<p>__end__</p>]):::last
	__start__ --> route;
	grade -.-> generate;
	grade -.-> rewrite;
	plan --> retrieve;
	retrieve --> grade;
	rewrite --> plan;
	route -.-> plan;
	route -.-> respond;
	generate --> __end__;
	respond --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
